name: on PR to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: update submodules
      working-directory: ${{github.workspace}}
      run: |
        git submodule update --init --recursive

    - name: build dev image
      working-directory: ${{github.workspace}}
      run: |
        docker build --network=host -t mcu-server-dev:latest -f docker/dev.dockerfile .

    - name: cmake config
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:/usr/app/src -v ${{github.workspace}}/bin:/usr/app/bin mcu-server-dev:latest cmake -DCMAKE_BUILD_TYPE=Debug -S /usr/app/src -B /usr/app/bin
    
    - name: run uts
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:/usr/app/src -v ${{github.workspace}}/bin:/usr/app/bin mcu-server-dev:latest cmake --build /usr/app/bin

    - name: run uts
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:/usr/app/src -v ${{github.workspace}}/bin:/usr/app/bin mcu-server-dev:latest cmake --build /usr/app/bin --target test
