name: Unit tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build dev image
      working-directory: ${{github.workspace}}
      id: build-dev-image
      run: |
        docker build --network=host -t mcu-server-dev:latest -f docker/dev.dockerfile .

    - name: Run UTs
      working-directory: ${{github.workspace}}/automation
      run: |
        docker run -it -v ${{github.workspace}}:/usr/app/src mcu-server-dev:latest python3 -u automation/run_ut_tests.py /usr/app/src
