name: Unit tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: build dev image
      working-directory: ${{github.workspace}}
      id: build-dev-image
      run: |
        docker build --network=host -t mcu-server=dev:latest -f docker/dev.dockerfile .

    - name: Run UTs
      working-directory: ${{github.workspace}}/automation
      run: |
        docker build -t mcu-server=dev:latest -f docker/dev.dockerfile . sudo apt-get update && sudo apt-get install -y libcpprest-dev && python -u run_ut_tests.py ${{github.workspace}}
